name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish_npm:
    if: "(github.repository == 'invertase/react-native-google-ads') && (github.event_name == 'workflow_dispatch')"
    name: 'NPM'
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Yarn Install
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 10
          retry_wait_seconds: 60
          max_attempts: 3
          command: yarn --no-audit --prefer-offline
      - name: GIT Setup
        run: |
          git config --global user.name '@Salakar'
          git config --global user.email 'Salakar@users.noreply.github.com'
          git remote set-url origin git@github.com:$GITHUB_REPOSITORY
      - name: Publish Packages
        run: |
          yarn logout
          echo "@invertase:registry=http://registry.npmjs.org/" > ~/.npmrc
          echo "registry=http://registry.npmjs.org/" >> ~/.npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          npm whoami
          git diff --exit-code
          yarn semantic-release -d
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
